openapi: 3.0.3
info:
  title: Shisha log v0
  description: |-
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
security: []
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://api-image-ie5amycdoa-uw.a.run.app 
tags:
  - name: user
    description: user関連のapi
  - name: diary
    description: Diary関連のapi
paths:
  /user/{user_id}/equipment:
    $ref: "./paths/user.{user_id}.equipment.yaml"
  /user/{user_id}/flavor:
    $ref: "./paths/user.{user_id}.flavor.yaml"
  /user/{user_id}/bottle:
    $ref: "./paths/user.{user_id}.bottle.yaml"
  /user/{user_id}/bowl:
    $ref: "./paths/user.{user_id}.bowl.yaml"
  /user/{user_id}/heat_management:
    $ref: "./paths/user.{user_id}.heat_management.yaml"
  /user/{user_id}/charcoal:
    $ref: "./paths/user.{user_id}.charcoal.yaml"
  /diary:
    $ref: "./paths/diary.yaml"
  /diary/{user_id}:
    $ref: "./paths/diary.{user_id}.yaml"
