name: Deploy OpenAPI Document to GitHub Pages

on:
    pull_request:
        branches:
            - master
        types:
            - opened
            - synchronize
            - closed
        paths:
            - docs/openapi.yaml
            - .github/workflows/deploy-openapi-docs-to-github-pages.yaml

jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install swagger-cli
              run: |
                npm install -g swagger-cli

            - name: Validate docs/openapi.yaml
              run: |
                swagger-cli validate -d docs/openapi.yaml --type yaml

            - name: Generate Swagger UI
              if: github.event.pull_request.merged == true
              uses: Legion2/swagger-ui-action@v1
              with:
                output: swagger-ui
                spec-file: docs/openapi.yaml

            - name: Deploy to GitHub Pages
              if: github.event.pull_request.merged == true
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: swagger-ui

permissions:
    contents: write
