name: Deploy OpenAPI Document to GitHub Pages

on:
    push:
        branches:
            - develop
        paths:
            - docs/openapi.yaml
            - docs/paths/**/*.yaml
            - docs/schemas/**/*.yaml
            - .github/workflows/deploy-openapi-docs-to-github-pages.yaml
    pull_request:
        branches:
            - develop
        types:
            - synchronize
            - closed
        paths:
            - docs/openapi.yaml
            - docs/paths/*.yaml
            - docs/schemas/*.yaml
            - .github/workflows/deploy-openapi-docs-to-github-pages.yaml

jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install swagger-cli
              run: |
                npm install -g swagger-cli
 
            - name: Bundle docs
              run: |
                swagger-cli bundle -o docs/openapi.yaml -t yaml docs/openapi.yaml

            - name: Validate docs/openapi.yaml
              run: |
                swagger-cli validate -d docs/openapi.yaml -t yaml

            - name: Generate Swagger UI
              uses: Legion2/swagger-ui-action@v1.2.0
              with:
                output: swagger-ui
                spec-file: docs/openapi.yaml


            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: swagger-ui

permissions:
    contents: write
